### ISSUE TITLE
Error: no matching function for call to ‘cv::xfeatures2d::SURF::SURF(int&)’

### ISSUE THREAD

**Issue by MiguelCanto** [Itseez/opencv_contrib#148]
'Morning.
I've installed over my already compiled and working OpenCV dist the opencv_contrib from this repository because im trying to use SURF.
The thing is that i've followed the steps from this page and is not working. It always returns me the same error.
Asking on the internet a guy told me that i need the library libopencv_xfeatures2d300.so but that file is not in the repo and it dosen't creates when i cmake.
The OpenCV forum is down and i'm a little desperate. 
Anyone knows what is happening?
Thank you in advance.

**Comment by techfort** [comment]
@MiguelCanto I know this is old but as I'm going through the API myself I can tell you that SURF and SIFT can be created using `cv2.xfeatures2d.SURF_create()` and `cv2.xfeatures2d.SIFT_create()`.
But make sure to check the latest version of opencv and contrib, which at this time are `3.0.0-rc1`. I'm sure key contributors will correct me if this is not the case.

**Comment by StevenPuttemans** [comment]
@MiguelCanto as @techfort suggested, that is the way to call it. The functionality is working perfectly fine for the moment. Be sure that both opencv and opencv_contrib repository have the same version [check by tag] in order to compile fine.

@mshabunin this can also be closed. Should be at https://answers.opencv.org/questions!
