### ISSUE TITLE
rst_parser module not found when compiling matlab binding

### ISSUE THREAD

**Issue by anuppari** [Itseez/opencv_contrib#167]
I'm trying to follow the instructions here http://seevisionc.blogspot.com/2014/03/compiling-opencv-30-with-matlab-support.html for compiling with matlab bindings. In cmake, I get errors that the rst_parser is not found. I see the hdr_parser module is in the modules/python/src2 folder but I don't see any rst_parser. Is this a separate python module? If so, where is it available ( a quick google search didn't provide any results)?

**Comment by mshabunin** [comment]
@anuppari, rst documentation has been removed from OpenCV along with _rst_parser_ script. 
You can try one of the following solutions:
- remove _rst_parser_ dependency from Matlab binding
- take older version of OpenCV sources (before [this commit](https://github.com/Itseez/opencv/commit/d01bedbc61b7febbb0d35a5978efb4c30709af5d))

**Comment by anuppari** [comment]
It looks like gen_matlab.py in the matlab module is still heavily dependent on rst_parser. What can be used to replace it?

**Comment by talbym** [comment]
Could someone drop a comment on this issue, when it is solved, over in the openCV user forum in the comment area of this [thread](http://answers.opencv.org/question/54990/bindings-to-access-opencv-from-matlab-do-not-generate/), please? I feel to still be too much beginner for bothering you here at github, because I could only mention problems I found, but not constructively add to the discussion are problem solving. Thanks to all of you who work on openCV, you are just great! Talby

**Comment by yifita** [comment]
if someone downloaded the earlier version of rst_parser, could you share it somewhere? i can no longer retrieve that file from old commits

**Comment by howtobeahacker** [comment]
@yifita @talbym  You can download rst_parser here https://github.com/Itseez/opencv/blob/d01bedbc61b7febbb0d35a5978efb4c30709af5d/modules/java/generator/rst_parser.py.
I downloaded and put it in my local corresponding folder, according to this solution [http://code.opencv.org/issues/4175]. And it works

**Comment by StevenPuttemans** [comment]
temporary solution can be found above and PR for adding it back is suggested for the moment :)

**Comment by StevenPuttemans** [comment]
PR merged and build just fine now! You can close this issue down!
