### ISSUE TITLE
how to report bug in Gender Recognition and Face Recognition tutorials

### ISSUE THREAD

**Issue by marilia15** [Itseez/opencv_contrib#403]
When it calls to `python create_csv.py ` it should be `python create_csv.py at ` where `at` is the `base_path` required by the script.

Also the links for download the source of both scripts `create_csv.py` and `aligning faces` are not in the page of the tutorial but they are mentioned to be in that page. 

Also in the tutorial does not include the information about the format of the training pictures, jpeg or png did not work in my case, pgm do.

The pages of the tutorials are
http://docs.opencv.org/modules/contrib/doc/facerec/tutorial/facerec_gender_classification.html
http://docs.opencv.org/modules/contrib/doc/facerec/tutorial/facerec_video_recognition.html

Sorry, because I do not know where to inform about these bugs. Is here the right place?

**Comment by StevenPuttemans** [comment]
If jpeg or png does not work, than it must be because you built opencv without support or because your platform is not supporting it, because I run the interface perfectly fine on png pictures.

As to the problems, this is the right place for issues and bug reports! Are you maybe up for supplying a PR with the fixes as explained here: https://github.com/Itseez/opencv/wiki/How_to_contribute?

**Comment by sturkmen72** [comment]
this can be closed down
